---
# file: roles/apache/handlers/main.yml
- name: install apche
  command: /sbin/insserv -f apache2

- name: restart apache
  service: name=apache2 state=restarted

- name: refersh consul
  service: name=consul state=reloaded
