---
# file: roles/consul-template/handlers/main.yml
- name: install consultemplate
  command: /sbin/insserv -f consul-template

- name: restart consultemplate
  service: name=consul-template state=restarted

- name: refresh consultemplate
  service: name=consul-template state=reloaded
