---
# file: roles/consul-template/handlers/main.yml
- name: install consultemplate
  command: /sbin/insserv -f consul-template{{ init_suffix }}

- name: restart consultemplate
  service: name=consul-template{{ init_suffix }} state=restarted

- name: refresh consultemplate
  service: name=consul-template{{ init_suffix }} state=reloaded
