---
- hosts: consulagents
  vars:
    ansible_environment: dev
  sudo: yes

  tasks:
  - name: Create Consul bin dir
    file: path=/usr/nano/bin state=directory

  - name: Install Consul
    copy: src=/usr/nano/build/go/bin/consul mode=744 dest=/usr/nano/bin/consul

  - name: Create Consul config folder
    file: path={{ consul_config_dir }} state=directory

  - name: Create Consul data dir
    file: path={{ consul_data_dir }} mode=755 state=directory

  - name: Create Consul log dir
    file: path={{ consul_log_dir }} mode=755 state=directory

  - name: Create Consul config
    template: src=templates/consulagent.json dest=/etc/consulagent.conf

  - name: Install consulagent config
    copy: src=files/init.d/consulagent mode=744 dest=/etc/init.d/consulagent

  - name: Run chkconfig to enable service
    command: /sbin/chkconfig --set consulagent on

  - name: Enable consulagent service
    command: /etc/init.d/consulagent start
