---
# This Playbook deploys the components for the webserver
#   Apache, consului and kibana

# setup and deploy apache
- hosts: appservers
  become: yes

  vars_prompt:
    - name: "ans_mode"
      prompt: "install or uninstall?"

  roles:
    - role: tomcat

  post_tasks:
    - name: refresh consul
      service: name=consul{{ init_suffix }} state=reloaded

    - name: refresh consul-template
      service: name=consul-template{{ init_suffix }} state=reloaded
