---
# This Playbook deploys the consul componets for consul server,
#   consul agent, and consul-template
#   consului is deployed with the webservers group

# setup and deploy consul servers and consul agents
- hosts: consulservers
  become: yes

  roles:
    - role: common
    - role: consul

- hosts: consulagents
  become: yes

  roles:
    - role: common
    - role: consul

# setup and deploy consul-template
- hosts: consultemplate
  become: yes

  roles:
    - role: common
    - role: consul-template
