---
# This Playbook deploys mongodb

# deploy mongo
- hosts: dbservers
  become: yes

  roles:
    - role: mongo-automation-agent

#  post_tasks:
#    - name: refresh consul
#      service: name=consul{{ init_suffix }} state=reloaded

#    - name: refresh consul-template
#      service: name=consul-template{{ init_suffix }} state=reloaded
