---
# This Playbook deploys mongodb

# deploy mongo
- hosts: dbservers
  become: yes

  roles:
    - role: mongod

  post_tasks:
    - name: refresh consul
      shell: 'kill -1 $(cat /var/run/consul.pid)'

    - name: refresh consul-template
      shell: 'kill -1 $(cat /var/run/consul-template.pid)'
