---

# This Playbook deploys elasticsearch and logstash

# deploy elasticsearch
- hosts: elasticsearch
  become: yes

  roles:
    - role: elasticsearch

# deploy logstash
- hosts: logstash
  become: yes

  roles:
    - role: logstash

  post_tasks:
    - name: refresh consul
      service: name=consul{{ init_suffix }} state=reloaded

    - name: refresh consul-template
      service: name=consul-template{{ init_suffix }} state=reloaded
