---
# This Playbook deploys mongodb

# deploy mongo
- hosts: opsdbservers
  become: yes

  roles:
    - role: mongod

- hosts: backupdbservers
  become: yes

  roles:
    -role: mongod

#  post_tasks:
#    - name: refresh consul
#      service: name=consul{{ init_suffix }} state=reloaded

#    - name: refresh consul-template
#      service: name=consul-template{{ init_suffix }} state=reloaded
