---
# This Playbook deploys the code and infrastructure to run a consul cluster
#   with ELK (elasticsearch, logstash, and kibana)
#   as well as the UI components for consul and Kibana

- include: clustering.yml
- include: webservers.yml
- include: logging.yml
