---
# This Playbook deploys the consul componets for consul server,
#   consul agent, and consul-template
#   consului is deployed with the webservers group
#
- hosts: aebbackend
  become: yes

  vars:
    tcat_cluster_name: "aebedx"

  vars_prompt:
    - name: "ans_mode"
      prompt: "install or uninstall?"

  roles:
    - role: tomcat
