---
# This Playbook deploys the components for the webserver
#   Apache, consului and kibana

# setup and deploy apache
- hosts: webservers
  become: yes

  handlers:
    - include: roles/consul-template/handlers/main.yml

  roles:
    - role: common
    - role: apache
    - role: consului
    - role: kibana

  post_tasks:
    - name: refresh consul
      shell: 'kill -1 $(cat /var/run/consul.pid)'

    - name: refresh consul-template
      shell: 'kill -1 $(cat /var/run/consul-template.pid)'
