---
# installs mongodb on server(s)
#   group_var: mongod_deploy -- single for stand-alone node; cluster for replication set

  - name: Ensure group is present
    group: name="{{ mongo_group }}" state=present

  - name: Create user to be used by dameon processes
    user: name="{{ mongo_user }}" comment="Nanotech Logging Services" group="{{ mongo_group }}"

  - name: Install mongo dependencies
    zypper: name={{ item }} state="latest"
    with_items:
     - "cyrus-sasl"
     - "krb5"
     - "libgcc46"
     - "libopenssl0_9_8"
     - "libsnmp15"
     - "libstdc++46"
     - "zlib"

  - name: Create Mongo app, data and log directories
    file: path={{ item }} state=directory owner={{ mongo_user }} group={{ mongo_group }} mode=755
    with_items:
     - "{{ inf_app_path }}/mongo"
     - "{{ db_data_path }}/mongo/mongod"
     - "{{ db_log_path }}"
     - "/var/run/mongodb"

# copy and unpack mongo executable archive
  - name: Install Mongo executables
    unarchive: src=/usr/nano/build/{{ ansible_environment }}/mongo/mongo-ent.tar.gz dest={{ inf_app_path }}/mongo owner={{ mongo_user }} group={{ mongo_group }}

  - name: Add bootstrap program and config
    copy: src="{{ item.src }}" dest={{ item.dest }} mode=777
    with_items:
      - { src: "/usr/nano/build/{{ ansible_environment }}/bootstrap/bootstrap", dest: "/tmp/bootstrap" }
      - { src: "bs_mongod.conf", dest: "/tmp/bs_mongod.conf" }

  - name: Add bootstrap tmpl file
    template: src=bs_mongod.tmpl dest=/tmp/bs_mongod.tmpl

  - name: Run bootstrap process
    command: /tmp/bootstrap -conf=/tmp/bs_mongod.conf -tmpl=/tmp/bs_mongod.tmpl -port={{ consul_port }}
    run_once: true

  - name: Add mongod status utility
    template: src="mongod_status.sh" dest="{{ inf_app_path }}/mongo/mongo_status.sh" mode=755

  - name: Add consul-template ctmpl file
    copy: src=mongod.{{ mongod_deploy }}.ctmpl dest={{ etc_conf}}/consul-template/ctmpl/mongod.ctmpl

  - name: Add file consul-template conf
    template: src=consul-template.conf dest={{ etc_conf }}/consul-template/conf.d/mongod mode=744

  - name: Add file consul service config
    template: src=mongod.json dest={{ etc_conf }}/consul.d/mongod.json mode=744

  - name: Install mongo init script
    template: src=mongod.init.d mode=744 dest=/etc/init.d/mongod
    notify:
      - install mongod
      - retart mongod
