---
# file: roles/mongod/tasks/replset.yml

- name: Copy replication set initiatlization scripts
  template: src={{ item.src }} dest={{ item.dest }}
  when: mongo_role == "primary"
  with_items:
   - { src: "user_init.js", dest: "/tmp/user_init.js" }
   - { src: "replset_init.js", dest: "/tmp/replset_init.js" }
   - { src: "replset_addhost.js", dest: "/tmp/replset_addhost.js" }

- name: Initiate replication set on primary
  shell: "{{ inf_app_path }}/mongo/mongo admin --port {{ mongod_port }} /tmp/replset_init.js > /tmp/rs.status"
  when: mongo_role == "primary"

- name: Set up siteUserAdmin
  shell: "{{ inf_app_path }}/mongo/mongo admin --port {{ mongod_port }} /tmp/user_init.js"
  when: mongo_role == "primary"

- name: Add additional hosts to replication set
  shell: "{{ inf_app_path }}/mongo/mongo admin --port {{ mongod_port }} /tmp/replset_addhost.js -u siteUserAdmin -p {{ mongo_admin_pwd }}"
  when: mongo_role == "primary"
