---
  - include_vars: roles/apache/vars/main.yml
      
  - name: Create consul ui directory in apache doc root
    file: path="{{ apache_doc_root }}/consului" state=directory owner="{{ apache_user }}" group="{{ apache_group }}" mode=744

  - name: Copy consul ui
    copy: src=/usr/nano/build/{{ ansible_environment }}/consului/ dest="{{ apache_doc_root}}/consului/" owner="{{ apache_user }}" group="{{ apache_group }}" mode=744

  - name: Add apache mod_proxy to connect to consul
    lineinfile: dest="{{ inf_app_path }}/apache2/conf/httpd.conf" regexp="^ProxyPass /v1" insertafter="^#ProxyPass" line="ProxyPass /v1/ http://localhost:{{ consul_port }}/v1/"
    notify: restart apache
