---
# file: roles/elasticsearch/handlers/main.yml
- name: install elasticsearch
  command: /sbin/insserv -f elasticsearch{{ init_suffix }}

- name: restart elasticsearch
  service: name=elasticsearch{{ init_suffix }} state=restarted
