---
  - name: Create consul-template directories (config, ctml, bin)
    file: path={{ item }} state=directory
    with_items:
      - "{{ consul_template_ctmpl_dir }}"
      - "{{ consul_template_config_dir }}"
      - "{{ inf_app_path }}/consul-template"

  - name: Process templates init.d
    template: src=consul-template.init.d dest=/etc/init.d/consul-template{{ init_suffix }} mode=744
    notify: 
      - install consultemplate
      - restart consultemplate

  - name: Install consul-template
    copy: src="/usr/nano/build/{{ ansible_environment}}/consul-template/consul-template" mode=744 dest="{{ inf_app_path }}/consul-template/consul-template"
    notify: restart consultemplate

  - name: Process config template
    template: src=01-consul-template.conf dest="{{ consul_template_config_dir }}/01-consul-template.conf" mode=744
    notify: refresh consultemplate
