SET LINESIZE 1024
DEFINE PARM_X_VALUE = &1

VARIABLE HV_X_VALUE_TRANS CHAR(20);
VARIABLE HV_X_VALUE CHAR(1024);

BEGIN
:HV_X_VALUE_TRANS := '&&PARM_X_VALUE';
--:HV_X_VALUE_TRANS := 'RNWLLTR1';
:HV_X_VALUE := ' ';
END;
/

--PRINT HV_X_VALUE_TRANS

BEGIN
SELECT SLY152_COL16.X_VALUE
INTO  :HV_X_VALUE
FROM   SLY152_SVVALUE SLY152_COL0, 
       SLY152_SVVALUE SLY152_COL16
WHERE  SLY152_COL0.X_NAME = 'SL_PROCESS_CNTL'
AND    SLY152_COL0.D_EFF = (SELECT MAX(D_EFF) FROM SLY152_SVVALUE WHERE X_NAME = 'SL_PROCESS_CNTL')
AND    SLY152_COL0.N_COLUMN = 0
--AND	   SLY152_COL0.X_VALUE = :HV_X_VALUE_TRANS --'RNWLLTR1' --:HV_X_VALUE_TRANS
AND	   SLY152_COL0.X_VALUE = '&&PARM_X_VALUE'
AND    SLY152_COL16.X_NAME = SLY152_COL0.X_NAME
AND    SLY152_COL16.D_EFF = SLY152_COL0.D_EFF
AND    SLY152_COL16.N_COLUMN = 16
AND    SLY152_COL16.N_ROW = SLY152_COL0.N_ROW;
END;
/

PRINT HV_X_VALUE

EXIT;
