---
  - name: Ensure group is present
    group: name="{{ inf_group }}" state=present

  - name: Create user to be used by dameon processes
    user: name="{{ elasticsearch_user }}" comment="Nanotech Logging Services" group="{{ inf_group }}"

  - name: Create directory structure (app, log, data)
    file: path={{ item }} state=directory group={{ inf_group }} owner={{ elasticsearch_user }} mode=755
    with_items:
      - "{{ inf_app_path }}/elasticsearch"
      - "{{ inf_log_path }}/elasticsearch"
      - "{{ inf_data_path }}/elasticsearch"

  - name: Check for current version
    command: "{{ inf_app_path }}/elasticsearch/current/bin/elasticsearch -v"
    register: vers_check
    failed_when: vers_check.rc > 2

  - name: Copy and extract elasticsearch
    unarchive: src="/usr/nano/build/{{ ansible_environment }}/elasticsearch/elasticsearch.tar.gz" dest="{{ inf_app_path }}/elasticsearch" owner="{{ elasticsearch_user }}" group="{{ inf_group }}"
    when: vers_check.rc > 0

  - name: Add bootstrap program and config
    copy: src="{{ item.src }}" dest={{ item.dest }} mode=777
    with_items:
      - { src: "/usr/nano/build/{{ ansible_environment }}/bootstrap/bootstrap", dest: "/tmp/bootstrap" }
      - { src: "bs_elasticsearch.conf", dest: "/tmp/bs_elasticsearch.conf" }

  - name: Add bootstrap tmpl file
    template: src=bs_elasticsearch.tmpl dest=/tmp/bs_elasticsearch.tmpl

  - name: Run bootstrap process
    command: /tmp/bootstrap -conf=/tmp/bs_elasticsearch.conf -tmpl=/tmp/bs_elasticsearch.tmpl -port={{ consul_port }}
    run_once: true

  - name: Add elasticsearch status utility
    copy: src="/usr/nano/build/{{ ansible_environment }}/status-utils/es_status" dest="{{ inf_app_path }}/elasticsearch/current/bin/es_status" mode=755

  - name: Add consul-template ctmpl file
    copy: src=elasticsearch.ctmpl dest={{ etc_conf }}/consul-template/ctmpl/elasticsearch.ctmpl

  - name: Add file consul-template conf
    template: src=consul-template.conf dest={{ etc_conf }}/consul-template/conf.d/elasticsearch mode=744

  - name: Add file consul service config
    template: src=elasticsearch.json.ctmpl dest={{ etc_conf }}/consul-template/ctmpl/elasticsearch.json.ctmpl mode=744

  - name: Add file init.d script
    template: src=elasticsearch.init.d dest=/etc/init.d/elasticsearch{{ init_suffix }} mode=744
    notify:
      - install elasticsearch
      - restart elasticsearch
