#!/bin/bash
#
# mongodb        Manage the mongodb agent
#       
# chkconfig:   2345 95 95
# description: Consul is a tool for service discovery and configuration
# processname: mongodb
# config: /etc/mongodb.conf
# pidfile: /var/run/mongodb.pid
 
### BEGIN INIT INFO
# Provides:       mongodb
# Required-Start: $local_fs $network consul
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop:  0 1 6
# Short-Description: Manage the mongodb agent
# Description: mongodb is document database
### END INIT INFO
 
prog="mongod"
user="root"
exec="/usr/nano/bin/$prog"
pidfile="/var/run/$prog.pid"
lockfile="/var/lock/subsys/$prog"
conffile="/etc/mongodb.conf"
 
# pull in sysconfig settings
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
 
start() {
    [ -x $exec ] || exit 5
    
    [ -f $conffile ] || exit 6
 
    umask 077
 
    touch $pidfile
    chown $user:$user $pidfile
 
    echo -n $"Starting $prog: $1"

    ## holy shell shenanigans, batman!
    ## daemon can't be backgrounded.  we need the pid of the spawned process,
    ## which is actually done via runuser thanks to --user.  you can't do "cmd
    ## &; action" but you can do "{cmd &}; action".
    /sbin/start_daemon -f \
        -p $pidfile \
        -u $user \
		$exec --config $conffile & echo $! > $pidfile
    
    RETVAL=$?
    echo
    
    [ $RETVAL -eq 0 ] && touch $lockfile
    
    return $RETVAL
}
 
stop() {
    echo -n $"Shutting down $prog: "
    ## graceful shutdown with SIGINT
    /sbin/start-stop-daemon -K -p $pidfile -u $user -x $exec -s 2
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}
 
restart() {
    stop
    start
}
 
reload() {
    echo -n $"Reloading $prog: "
    /sbin/start-stop-daemon -K -p $pidfile -u $user -x $exec -s 9
    echo
}
 
force_reload() {
    restart
}
 
rh_status() {
   PID="$(sed -ne 's|^[\t\v\f ]*\([0-9]\+\)[\t\v\f ]*$|\1|p' $pidfile | tr -s '[[:space:][:cntrl:]]' ' ')"
   if [ $PID -eq $(pidof $prog) ]
      then
	$exec --version
	return 0
   fi
   return 2
}
 
rh_status_q() {
    rh_status >/dev/null 2>&1
}
 
case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        $1
        ;;
    bootstrap)
        start $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|bootstrap|reload|force-reload}"
        exit 2
esac
 
exit $?
