---
# file: roles/consul-template/handlers/main.yml
- name: refresh consultemplate
  shell: 'kill -1 $(cat /var/run/consul-template.pid)'

- name: install consultemplate
  command: /sbin/insserv -f consul-template

- name: restart consultemplate
  service: name=consul-template state=restarted

